#! /usr/bin/env node

var exec = require('child_process').exec,
    fs = require('fs');

const MODULE_INFO = (function (manifest) {
    return {
        VERSION: manifest.match(/version: ([\S]+)/m)[1],
        NAME: manifest.match(/name: ([\S]+)/m)[1]
    };
}(fs.readFileSync('manifest').toString()));

console.log(MODULE_INFO.NAME, "v" + MODULE_INFO.VERSION);

exec('mv ' + MODULE_INFO.NAME + '.js __save', function () {
    exec('browserify -s ' + MODULE_INFO.NAME + ' -o __temp.js __save', function () {
        exec('uglify -s __temp.js -o ' + MODULE_INFO.NAME +'.js', function () {
            var destFolder = 'modules/commonjs/' + MODULE_INFO.NAME + '/' + MODULE_INFO.VERSION;
            exec('mkdir -p ' + destFolder + ' && cp manifest timodule.xml ' + MODULE_INFO.NAME + '.js ' + destFolder, function () {
                exec('zip -r ' + MODULE_INFO.NAME + '-commonjs-' + MODULE_INFO.VERSION + '.zip ' + destFolder, function () {
                    exec('rm -r modules __temp.js && mv __save ' + MODULE_INFO.NAME + '.js', function () {
                        console.log("Build Successful!");
                    });
                });
            });
        });
    });
});
